kind: pipeline
type: docker
name: build

steps:
- name: build
  image: golang:alpine
  commands:
  - go get
  - go build -o mcmod
  - test -z "$(gofmt -l . | tee /dev/stderr)"

- name: run
  image: alpine
  commands:
  - ./mcmod -l trace get notenoughitems

---
kind: pipeline
type: docker
name: lint

steps:
- name: lint
  image: golang:alpine
  commands:
  - go get -u golang.org/x/lint/golint
  # when all the lint errors go away, we can actually fail on it
  #- golint -set_exit_status ./...
  - golint ./...

---
kind: pipeline
type: docker
name: test

steps:
- name: unit
  image: golang:alpine
  commands:
  - apk --no-cache add gcc musl-dev
  - go test -covermode atomic ./...
